name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    
    strategy:
      matrix:
        package: [XZCore, XZNetworking, XZFileUtils, XZFoundationUtils, XZUIKitUtils, XZAppKitUtils, XZUIComponents]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build ${{ matrix.package }}
      run: |
        cd Packages/${{ matrix.package }}
        swift build
        
    - name: Test ${{ matrix.package }}
      run: |
        cd Packages/${{ matrix.package }}
        swift test

  build-all:
    name: Build All Packages
    runs-on: macos-latest
    needs: build-and-test
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build All
      run: ./Scripts/build-all.sh
      
    - name: Test All
      run: ./Scripts/test-all.sh